In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score

In [2]:
k = 5
rep = 100
r_s2_test = []
r_s5_test = []
r_s10_test = []
r_s10_l2_test = []

In [3]:
f_s2_test = []
f_s5_test = []
f_s10_test = []
f_s10_l2_test = []

In [4]:
def m_distance(x1,x2,cov_m):
    return( np.dot(np.dot( (x1 - x2).T, np.linalg.inv(cov_m) ), (x1 - x2)) )

## s2

In [6]:
for label in range(rep):
    
    label = label + 1
    print(label)
    rountine = 'D:/研究生文件/科研任务/functional_data/sim_data/s2/'
    file_data = rountine + 'all_data_0801(2)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_x = my_data[:,1:len(my_data[0,:])]
    n = len(my_x[:,0])
    x_dim = len(my_x[0,:])

    file_data = rountine + 'y_label_0801(2)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_y = my_data[:,1] - 1 ##注意减一
    my_y = my_y.reshape((len(my_y),1))

    file_data = rountine + 'all_data_test_0801(2)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_x_test = my_data[:,1:len(my_data[0,:])]
    n_test = len(my_x_test[:,0])
    x_dim = len(my_x_test[0,:])

    file_data = rountine + 'y_label_test_0801(2)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_y_test = my_data[:,1] - 1 ##注意减一
    my_y_test = my_y_test.reshape((len(my_y),1))
    
    
    label_sum = np.zeros((k,x_dim))
    label_num = np.zeros(k)
    label_cov = np.zeros((k,x_dim,x_dim)) ###
    
    for i in range(n):
        i_label = my_y[i,0]
        label_num[i_label] += 1
        label_sum[i_label,:] += my_x[i,:]
    
    label_mean = np.zeros((k,x_dim))
    for i in range(k):
        label_mean[i,:] = label_sum[i,:]/label_num[i]
        label_cov[i,:] = np.cov( ((my_x[np.where(my_y[:,0] == i),:])[0,:]) , rowvar=False) ###
        
    
    correct_num = 0
    esti_mat = np.zeros(n)
    for i in range(n):
        esti = np.zeros(k)
        for j in range(k):
            esti[j] = m_distance(my_x[i,:],label_mean[j,:], label_cov[j,:]) - np.log(label_num[j]) + 0.5*np.log(np.linalg.det(label_cov[j,:]))###
        esti_mat[i] = esti.argmin()
        if esti.argmin() == my_y[i]:
            correct_num += 1
    print(correct_num/n)
    

    correct_num = 0
    esti_mat_test = np.zeros(n_test)
    for i in range(n_test):
        esti = np.zeros(k)
        for j in range(k):
            esti[j] = m_distance(my_x_test[i,:],label_mean[j,:], label_cov[j,:]) - np.log(label_num[j]) + 0.5*np.log(np.linalg.det(label_cov[j,:])) ###

        esti_mat_test[i] = esti.argmin()
        if esti.argmin() == my_y_test[i]:
            correct_num += 1

    cf_mat = np.zeros((k,k))
    for i in range(n_test):
        cf_mat[int(my_y_test[i]),int(esti_mat_test[i])] += 1
        
    print(correct_num/n_test)
    print(cf_mat)
    r_s2_test.append(correct_num/n_test)
    f_s2_test.append(f1_score(my_y_test, esti_mat_test, average='macro'))

1
0.9466666666666667
0.8733333333333333
[[26.  0.  0.  7.  8.]
 [ 0. 39.  0.  4.  0.]
 [ 0.  6. 93.  0.  0.]
 [ 8.  3.  0. 45.  0.]
 [ 2.  0.  0.  0. 59.]]
2
0.9333333333333333
0.9
[[36.  0.  0.  4.  2.]
 [ 0. 55.  0.  4.  0.]
 [ 0.  6. 60.  0.  0.]
 [ 2.  8.  0. 57.  0.]
 [ 4.  0.  0.  0. 62.]]
3
0.94
0.8933333333333333
[[26.  0.  0.  4.  3.]
 [ 0. 53.  1.  0.  0.]
 [ 0.  7. 78.  0.  0.]
 [ 5. 11.  0. 43.  0.]
 [ 1.  0.  0.  0. 68.]]
4
0.9266666666666666
0.8633333333333333
[[25.  0.  0.  7.  6.]
 [ 0. 45.  0.  1.  0.]
 [ 0. 11. 74.  0.  0.]
 [ 8.  4.  0. 53.  0.]
 [ 4.  0.  0.  0. 62.]]
5
0.91
0.85
[[22.  0.  0. 11. 10.]
 [ 0. 37.  0.  3.  0.]
 [ 0.  4. 88.  0.  0.]
 [ 6. 10.  0. 45.  0.]
 [ 1.  0.  0.  0. 63.]]
6
0.93
0.9066666666666666
[[39.  0.  0.  4.  8.]
 [ 0. 51.  1.  0.  0.]
 [ 0.  4. 73.  0.  0.]
 [ 6.  5.  0. 50.  0.]
 [ 0.  0.  0.  0. 59.]]
7
0.94
0.88
[[26.  0.  0.  4. 10.]
 [ 0. 55.  0.  0.  0.]
 [ 0.  4. 76.  0.  0.]
 [ 9.  9.  0. 50.  0.]
 [ 0.  0.  0.  0. 57.]]
8
0.946

60
0.9333333333333333
0.89
[[29.  0.  0.  8.  3.]
 [ 0. 46.  6.  2.  0.]
 [ 0.  2. 95.  0.  0.]
 [ 6.  5.  0. 48.  0.]
 [ 1.  0.  0.  0. 49.]]
61
0.9333333333333333
0.91
[[24.  0.  0.  1. 10.]
 [ 0. 51.  1.  3.  0.]
 [ 0.  1. 74.  0.  0.]
 [ 6.  5.  0. 45.  0.]
 [ 0.  0.  0.  0. 79.]]
62
0.9333333333333333
0.9133333333333333
[[25.  0.  0.  4.  4.]
 [ 0. 54.  0.  1.  0.]
 [ 0.  4. 74.  0.  0.]
 [ 4.  9.  0. 45.  0.]
 [ 0.  0.  0.  0. 76.]]
63
0.9333333333333333
0.8866666666666667
[[29.  0.  0.  1. 13.]
 [ 0. 48.  1.  4.  0.]
 [ 0.  5. 76.  0.  0.]
 [ 3.  7.  0. 51.  0.]
 [ 0.  0.  0.  0. 62.]]
64
0.94
0.87
[[18.  0.  0.  9. 11.]
 [ 0. 37.  1.  9.  0.]
 [ 0.  2. 82.  0.  0.]
 [ 5.  2.  0. 62.  0.]
 [ 0.  0.  0.  0. 62.]]
65
0.9466666666666667
0.8566666666666667
[[22.  0.  0.  9. 10.]
 [ 0. 38.  0.  1.  0.]
 [ 0.  6. 69.  1.  0.]
 [ 5.  9.  0. 56.  0.]
 [ 2.  0.  0.  0. 72.]]
66
0.95
0.8966666666666666
[[26.  0.  0.  6.  7.]
 [ 0. 59.  0.  0.  0.]
 [ 0.  8. 75.  0.  0.]
 [ 2.  5.  0. 48. 

In [7]:
print(r_s2_test)
print(np.mean(r_s2_test))
print(np.std(r_s2_test))

print(f_s2_test)
print(np.mean(f_s2_test))
print(np.std(f_s2_test))

[0.8733333333333333, 0.9, 0.8933333333333333, 0.8633333333333333, 0.85, 0.9066666666666666, 0.88, 0.85, 0.89, 0.8866666666666667, 0.8766666666666667, 0.8866666666666667, 0.8733333333333333, 0.8866666666666667, 0.92, 0.8733333333333333, 0.8933333333333333, 0.8566666666666667, 0.8933333333333333, 0.8833333333333333, 0.86, 0.87, 0.88, 0.9033333333333333, 0.8966666666666666, 0.8933333333333333, 0.9233333333333333, 0.9166666666666666, 0.88, 0.86, 0.8966666666666666, 0.9033333333333333, 0.8733333333333333, 0.92, 0.8633333333333333, 0.9, 0.88, 0.89, 0.8866666666666667, 0.89, 0.9166666666666666, 0.8966666666666666, 0.9, 0.89, 0.8966666666666666, 0.87, 0.87, 0.8833333333333333, 0.9166666666666666, 0.91, 0.89, 0.8833333333333333, 0.88, 0.8566666666666667, 0.91, 0.8866666666666667, 0.9033333333333333, 0.9166666666666666, 0.9033333333333333, 0.89, 0.91, 0.9133333333333333, 0.8866666666666667, 0.87, 0.8566666666666667, 0.8966666666666666, 0.87, 0.8666666666666667, 0.8533333333333334, 0.88, 0.86, 0.

In [21]:
np.log(np.linalg.det(label_cov[4,:]))

-21.896670476061235

## s5

In [8]:
for label in range(rep):
    
    label = label + 1
    print(label)
    rountine = 'D:/研究生文件/科研任务/functional_data/sim_data/s5/'
    file_data = rountine + 'all_data_0801(5)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_x = my_data[:,1:len(my_data[0,:])]
    n = len(my_x[:,0])
    x_dim = len(my_x[0,:])

    file_data = rountine + 'y_label_0801(5)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_y = my_data[:,1] - 1 ##注意减一
    my_y = my_y.reshape((len(my_y),1))

    file_data = rountine + 'all_data_test_0801(5)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_x_test = my_data[:,1:len(my_data[0,:])]
    n_test = len(my_x_test[:,0])
    x_dim = len(my_x_test[0,:])

    file_data = rountine + 'y_label_test_0801(5)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_y_test = my_data[:,1] - 1 ##注意减一
    my_y_test = my_y_test.reshape((len(my_y),1))
    
    
    label_sum = np.zeros((k,x_dim))
    label_num = np.zeros(k)
    label_cov = np.zeros((k,x_dim,x_dim))
    
    for i in range(n):
        i_label = my_y[i,0]
        label_num[i_label] += 1
        label_sum[i_label,:] += my_x[i,:]
    
    label_mean = np.zeros((k,x_dim))
    for i in range(k):
        label_mean[i,:] = label_sum[i,:]/label_num[i]
        label_cov[i,:] = np.cov( ((my_x[np.where(my_y[:,0] == i),:])[0,:]) , rowvar=False)
        
    
    correct_num = 0
    esti_mat = np.zeros(n)
    for i in range(n):
        esti = np.zeros(k)
        for j in range(k):
            esti[j] = m_distance(my_x[i,:],label_mean[j,:], label_cov[j,:])
        esti_mat[i] = esti.argmin()
        if esti.argmin() == my_y[i]:
            correct_num += 1
    print(correct_num/n)
    

    correct_num = 0
    esti_mat_test = np.zeros(n_test)
    for i in range(n_test):
        esti = np.zeros(k)
        for j in range(k):
            esti[j] = m_distance(my_x_test[i,:],label_mean[j,:], label_cov[j,:])

        esti_mat_test[i] = esti.argmin()
        if esti.argmin() == my_y_test[i]:
            correct_num += 1

    cf_mat = np.zeros((k,k))
    for i in range(n_test):
        cf_mat[int(my_y_test[i]),int(esti_mat_test[i])] += 1
        
    print(correct_num/n_test)
    print(cf_mat)
    r_s5_test.append(correct_num/n_test)
    f_s5_test.append(f1_score(my_y_test, esti_mat_test, average='macro'))

1
0.9033333333333333
0.81
[[38.  1.  0.  5.  3.]
 [ 1. 38.  4.  0.  0.]
 [ 0.  4. 74.  6.  5.]
 [ 7.  8.  1. 44.  2.]
 [ 6.  0.  3.  1. 49.]]
2
0.9233333333333333
0.82
[[50.  1.  0.  6.  3.]
 [ 2. 33. 15.  2.  0.]
 [ 0.  2. 81.  2.  3.]
 [ 1.  3.  1. 55.  4.]
 [ 9.  0.  0.  0. 27.]]
3
0.9133333333333333
0.8233333333333334
[[40.  1.  0. 10.  0.]
 [ 0. 33.  5.  3.  0.]
 [ 3.  7. 96.  6.  3.]
 [ 4.  1.  1. 48.  1.]
 [ 8.  0.  0.  0. 30.]]
4
0.9133333333333333
0.8366666666666667
[[48.  0.  0.  7.  2.]
 [ 1. 33.  6.  1.  1.]
 [ 0.  2. 79.  0.  3.]
 [ 8.  0. 10. 50.  2.]
 [ 3.  2.  1.  0. 41.]]
5
0.92
0.83
[[34.  2.  0.  7.  0.]
 [ 1. 45.  3.  0.  0.]
 [ 0.  7. 93.  0.  3.]
 [ 7.  3.  6. 44.  0.]
 [11.  0.  1.  0. 33.]]
6
0.8866666666666667
0.85
[[42.  2.  0.  5.  8.]
 [ 1. 37.  1.  1.  0.]
 [ 1.  0. 86.  4.  4.]
 [ 8.  4.  0. 42.  1.]
 [ 4.  0.  1.  0. 48.]]
7
0.9066666666666666
0.8566666666666667
[[41.  2.  0. 12.  2.]
 [ 0. 31.  7.  5.  0.]
 [ 0.  0. 95.  2.  1.]
 [ 1.  0.  3. 49.  2.]
 [

57
0.92
0.8333333333333334
[[50.  4.  0.  7.  3.]
 [ 2. 27. 11.  7.  0.]
 [ 1.  0. 78.  4.  2.]
 [ 1.  1.  2. 57.  2.]
 [ 1.  0.  2.  0. 38.]]
58
0.94
0.8433333333333334
[[49.  1.  0.  5.  5.]
 [ 1. 29.  6.  4.  0.]
 [ 2.  3. 73.  3.  1.]
 [ 1.  1.  2. 46.  4.]
 [ 6.  0.  2.  0. 56.]]
59
0.8966666666666666
0.8066666666666666
[[52.  2.  0.  7.  1.]
 [ 0. 35. 10.  2.  0.]
 [ 3.  0. 78.  4.  0.]
 [ 3.  0.  7. 45.  1.]
 [18.  0.  0.  0. 32.]]
60
0.87
0.85
[[63.  0.  0.  5.  3.]
 [ 0. 35.  1.  3.  0.]
 [ 1.  4. 76.  3.  4.]
 [ 2.  3.  4. 44.  2.]
 [ 8.  1.  1.  0. 37.]]
61
0.9166666666666666
0.82
[[56.  1.  0.  9.  1.]
 [ 2. 32.  7.  3.  1.]
 [ 0.  1. 78.  3.  0.]
 [ 0.  1.  5. 42.  1.]
 [10.  0.  8.  1. 38.]]
62
0.9066666666666666
0.7866666666666666
[[49.  1.  0.  8.  1.]
 [ 2. 25. 11. 12.  0.]
 [ 1.  0. 80.  3.  2.]
 [ 4.  2.  5. 44.  3.]
 [ 3.  0.  5.  1. 38.]]
63
0.93
0.83
[[37.  4.  0. 11.  5.]
 [ 0. 34.  5.  3.  3.]
 [ 0.  0. 79.  7.  3.]
 [ 1.  0.  3. 58.  3.]
 [ 1.  0.  2.  0. 41.]]

In [9]:
print(r_s5_test)
print(np.mean(r_s5_test))
print(np.std(r_s5_test))

print(f_s5_test)
print(np.mean(f_s5_test))
print(np.std(f_s5_test))

[0.81, 0.82, 0.8233333333333334, 0.8366666666666667, 0.83, 0.85, 0.8566666666666667, 0.8666666666666667, 0.83, 0.82, 0.8133333333333334, 0.8, 0.7866666666666666, 0.8433333333333334, 0.8566666666666667, 0.8033333333333333, 0.8366666666666667, 0.8133333333333334, 0.8066666666666666, 0.8333333333333334, 0.7966666666666666, 0.83, 0.78, 0.85, 0.8533333333333334, 0.84, 0.8333333333333334, 0.8333333333333334, 0.8566666666666667, 0.84, 0.8333333333333334, 0.8266666666666667, 0.8466666666666667, 0.8, 0.8166666666666667, 0.8466666666666667, 0.7533333333333333, 0.84, 0.8466666666666667, 0.8166666666666667, 0.85, 0.83, 0.82, 0.8733333333333333, 0.8333333333333334, 0.86, 0.8633333333333333, 0.83, 0.8366666666666667, 0.8366666666666667, 0.82, 0.78, 0.8333333333333334, 0.8633333333333333, 0.8233333333333334, 0.8266666666666667, 0.8333333333333334, 0.8433333333333334, 0.8066666666666666, 0.85, 0.82, 0.7866666666666666, 0.83, 0.84, 0.8133333333333334, 0.8533333333333334, 0.8566666666666667, 0.846666666

## s10

In [10]:
for label in range(rep):
    
    label = label + 1
    print(label)
    rountine = 'D:/研究生文件/科研任务/functional_data/sim_data/s10/'
    file_data = rountine + 'all_data_0801(10)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_x = my_data[:,1:len(my_data[0,:])]
    n = len(my_x[:,0])
    x_dim = len(my_x[0,:])

    file_data = rountine + 'y_label_0801(10)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_y = my_data[:,1] - 1 ##注意减一
    my_y = my_y.reshape((len(my_y),1))

    file_data = rountine + 'all_data_test_0801(10)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_x_test = my_data[:,1:len(my_data[0,:])]
    n_test = len(my_x_test[:,0])
    x_dim = len(my_x_test[0,:])

    file_data = rountine + 'y_label_test_0801(10)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_y_test = my_data[:,1] - 1 ##注意减一
    my_y_test = my_y_test.reshape((len(my_y),1))
    
    
    label_sum = np.zeros((k,x_dim))
    label_num = np.zeros(k)
    label_cov = np.zeros((k,x_dim,x_dim))
    
    for i in range(n):
        i_label = my_y[i,0]
        label_num[i_label] += 1
        label_sum[i_label,:] += my_x[i,:]
    
    label_mean = np.zeros((k,x_dim))
    for i in range(k):
        label_mean[i,:] = label_sum[i,:]/label_num[i]
        label_cov[i,:] = np.cov( ((my_x[np.where(my_y[:,0] == i),:])[0,:]) , rowvar=False)
        
    
    correct_num = 0
    esti_mat = np.zeros(n)
    for i in range(n):
        esti = np.zeros(k)
        for j in range(k):
            esti[j] = m_distance(my_x[i,:],label_mean[j,:], label_cov[j,:])
        esti_mat[i] = esti.argmin()
        if esti.argmin() == my_y[i]:
            correct_num += 1
    print(correct_num/n)
    

    correct_num = 0
    esti_mat_test = np.zeros(n_test)
    for i in range(n_test):
        esti = np.zeros(k)
        for j in range(k):
            esti[j] = m_distance(my_x_test[i,:],label_mean[j,:], label_cov[j,:])

        esti_mat_test[i] = esti.argmin()
        if esti.argmin() == my_y_test[i]:
            correct_num += 1

    cf_mat = np.zeros((k,k))
    for i in range(n_test):
        cf_mat[int(my_y_test[i]),int(esti_mat_test[i])] += 1
        
    print(correct_num/n_test)
    print(cf_mat)
    r_s10_test.append(correct_num/n_test)
    f_s10_test.append(f1_score(my_y_test, esti_mat_test, average='macro'))

1
0.94
0.7833333333333333
[[43.  1.  0. 11.  2.]
 [ 1. 36. 17.  4.  0.]
 [ 1.  1. 82.  7.  3.]
 [ 2.  0.  3. 50.  0.]
 [ 8.  0.  3.  1. 24.]]
2
0.9466666666666667
0.8333333333333334
[[53.  2.  0.  2.  7.]
 [ 1. 28. 10.  0.  0.]
 [ 0.  0. 87.  0.  2.]
 [ 4.  4.  6. 48.  4.]
 [ 3.  0.  3.  2. 34.]]
3
0.9533333333333334
0.78
[[49.  1.  0.  4.  3.]
 [ 1. 16. 18.  6.  2.]
 [ 2.  1. 79.  1.  4.]
 [ 3.  0.  1. 49.  1.]
 [11.  0.  5.  2. 41.]]
4
0.9166666666666666
0.7366666666666667
[[53.  3.  1.  3.  0.]
 [ 1. 30. 15.  3.  0.]
 [ 2.  2. 69.  5.  0.]
 [14.  3.  5. 36.  2.]
 [14.  0.  5.  1. 33.]]
5
0.9566666666666667
0.8133333333333334
[[50.  1.  1.  3.  1.]
 [ 2. 40.  5.  4.  0.]
 [ 0.  6. 84.  1.  2.]
 [11.  3.  2. 39.  1.]
 [ 7.  2.  3.  1. 31.]]
6
0.92
0.7633333333333333
[[55.  1.  1.  1.  5.]
 [ 0. 20. 14.  1.  0.]
 [ 2.  2. 80.  4.  3.]
 [ 5.  4.  5. 47.  1.]
 [17.  0.  5.  0. 27.]]
7
0.9533333333333334
0.6766666666666666
[[46.  2.  0.  5.  8.]
 [ 2. 20. 20. 16.  1.]
 [ 1.  4. 75.  1.  6

0.76
[[52.  0.  1.  3.  4.]
 [ 1. 30. 13.  9.  0.]
 [ 0.  0. 65.  0.  7.]
 [ 9.  0.  8. 43.  5.]
 [ 8.  0.  2.  2. 38.]]
60
0.9533333333333334
0.8166666666666667
[[58.  3.  1. 10.  4.]
 [ 0. 31. 14.  0.  0.]
 [ 0.  0. 73.  4.  0.]
 [ 3.  2.  2. 45.  1.]
 [ 5.  0.  4.  2. 38.]]
61
0.96
0.8033333333333333
[[44.  0.  0.  5.  1.]
 [ 4. 28. 12.  2.  0.]
 [ 1.  1. 82.  4.  3.]
 [10.  1.  0. 46.  3.]
 [ 7.  0.  3.  2. 41.]]
62
0.9433333333333334
0.78
[[51.  4.  0.  1.  6.]
 [ 2. 40. 21.  0.  1.]
 [ 0.  3. 69.  1.  3.]
 [ 2.  5.  5. 44.  4.]
 [ 6.  0.  2.  0. 30.]]
63
0.9333333333333333
0.7433333333333333
[[54.  2.  0.  5.  4.]
 [ 3. 16. 23.  1.  1.]
 [ 3.  0. 75.  4.  4.]
 [ 5.  0.  9. 48.  1.]
 [ 4.  0.  7.  1. 30.]]
64
0.96
0.79
[[63.  1.  0.  4.  3.]
 [ 2. 30. 13.  0.  0.]
 [ 0.  4. 70.  2.  0.]
 [ 8.  3.  4. 47.  6.]
 [11.  1.  0.  1. 27.]]
65
0.9533333333333334
0.7933333333333333
[[51.  2.  0.  3.  3.]
 [ 0. 27. 15.  0.  1.]
 [ 0.  0. 84.  2.  4.]
 [11.  3.  3. 34.  1.]
 [ 7.  0.  6.  1.

In [11]:
print(r_s10_test)
print(np.mean(r_s10_test))
print(np.std(r_s10_test))

print(f_s10_test)
print(np.mean(f_s10_test))
print(np.std(f_s10_test))

[0.7833333333333333, 0.8333333333333334, 0.78, 0.7366666666666667, 0.8133333333333334, 0.7633333333333333, 0.6766666666666666, 0.81, 0.7933333333333333, 0.75, 0.76, 0.76, 0.7833333333333333, 0.7866666666666666, 0.75, 0.79, 0.81, 0.7633333333333333, 0.7566666666666667, 0.7766666666666666, 0.79, 0.73, 0.8033333333333333, 0.7833333333333333, 0.8166666666666667, 0.8066666666666666, 0.8033333333333333, 0.7566666666666667, 0.7933333333333333, 0.7866666666666666, 0.8266666666666667, 0.8066666666666666, 0.75, 0.76, 0.7966666666666666, 0.8533333333333334, 0.7766666666666666, 0.7233333333333334, 0.7833333333333333, 0.74, 0.79, 0.8033333333333333, 0.75, 0.7733333333333333, 0.7166666666666667, 0.7766666666666666, 0.7733333333333333, 0.8266666666666667, 0.7966666666666666, 0.79, 0.7033333333333334, 0.79, 0.7733333333333333, 0.76, 0.76, 0.74, 0.7866666666666666, 0.7833333333333333, 0.76, 0.8166666666666667, 0.8033333333333333, 0.78, 0.7433333333333333, 0.79, 0.7933333333333333, 0.8033333333333333, 0

## s10 - l2

In [12]:
for label in range(rep):
    
    label = label + 1
    print(label)
    rountine = 'D:/研究生文件/科研任务/functional_data/sim_data/s10_l2/'
    file_data = rountine + 'all_data_0801(10_l2)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_x = my_data[:,1:len(my_data[0,:])]
    n = len(my_x[:,0])
    x_dim = len(my_x[0,:])

    file_data = rountine + 'y_label_0801(10_l2)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_y = my_data[:,1] - 1 ##注意减一
    my_y = my_y.reshape((len(my_y),1))

    file_data = rountine + 'all_data_test_0801(10_l2)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_x_test = my_data[:,1:len(my_data[0,:])]
    n_test = len(my_x_test[:,0])
    x_dim = len(my_x_test[0,:])

    file_data = rountine + 'y_label_test_0801(10_l2)_' + str(label) + '.csv'
    data = pd.read_csv(file_data)
    my_data = data.values

    my_y_test = my_data[:,1] - 1 ##注意减一
    my_y_test = my_y_test.reshape((len(my_y),1))
    
    
    label_sum = np.zeros((k,x_dim))
    label_num = np.zeros(k)
    label_cov = np.zeros((k,x_dim,x_dim))
    
    for i in range(n):
        i_label = my_y[i,0]
        label_num[i_label] += 1
        label_sum[i_label,:] += my_x[i,:]
    
    label_mean = np.zeros((k,x_dim))
    for i in range(k):
        label_mean[i,:] = label_sum[i,:]/label_num[i]
        label_cov[i,:] = np.cov( ((my_x[np.where(my_y[:,0] == i),:])[0,:]) , rowvar=False)
        
    
    correct_num = 0
    esti_mat = np.zeros(n)
    for i in range(n):
        esti = np.zeros(k)
        for j in range(k):
            esti[j] = m_distance(my_x[i,:],label_mean[j,:], label_cov[j,:])
        esti_mat[i] = esti.argmin()
        if esti.argmin() == my_y[i]:
            correct_num += 1
    print(correct_num/n)
    

    correct_num = 0
    esti_mat_test = np.zeros(n_test)
    for i in range(n_test):
        esti = np.zeros(k)
        for j in range(k):
            esti[j] = m_distance(my_x_test[i,:],label_mean[j,:], label_cov[j,:])

        esti_mat_test[i] = esti.argmin()
        if esti.argmin() == my_y_test[i]:
            correct_num += 1

    cf_mat = np.zeros((k,k))
    for i in range(n_test):
        cf_mat[int(my_y_test[i]),int(esti_mat_test[i])] += 1
        
    print(correct_num/n_test)
    print(cf_mat)
    r_s10_l2_test.append(correct_num/n_test)
    f_s10_l2_test.append(f1_score(my_y_test, esti_mat_test, average='macro'))

1
0.98
0.82
[[18.  0.  0. 22.  4.]
 [ 0. 37.  5. 13.  0.]
 [ 0.  3. 75.  0.  0.]
 [ 0.  3.  0. 53.  0.]
 [ 4.  0.  0.  0. 63.]]
2
0.9766666666666667
0.81
[[33.  0.  0.  6.  6.]
 [ 0. 27. 13.  4.  0.]
 [ 0.  1. 76.  0.  0.]
 [11.  4.  1. 50.  0.]
 [11.  0.  0.  0. 57.]]
3
0.9766666666666667
0.79
[[24.  0.  0. 10. 10.]
 [ 0. 34.  5. 15.  0.]
 [ 0.  5. 65.  3.  0.]
 [ 7.  2.  0. 65.  0.]
 [ 6.  0.  0.  0. 49.]]
4
0.9733333333333334
0.7533333333333333
[[ 9.  0.  0. 22. 17.]
 [ 0. 16. 10. 17.  0.]
 [ 0.  1. 79.  0.  0.]
 [ 1.  4.  0. 66.  0.]
 [ 2.  0.  0.  0. 56.]]
5
0.9733333333333334
0.82
[[18.  0.  0. 13.  9.]
 [ 0. 26.  7. 11.  0.]
 [ 0.  1. 82.  0.  0.]
 [ 5.  2.  0. 50.  0.]
 [ 6.  0.  0.  0. 70.]]
6
0.9566666666666667
0.82
[[14.  0.  0. 18.  6.]
 [ 0. 36.  4.  9.  0.]
 [ 0.  6. 86.  0.  0.]
 [ 2.  2.  1. 49.  0.]
 [ 6.  0.  0.  0. 61.]]
7
0.9633333333333334
0.88
[[ 17.   0.   0.   9.   5.]
 [  0.  28.   6.   7.   0.]
 [  0.   2. 110.   0.   0.]
 [  3.   2.   1.  60.   0.]
 [  1.   0

0.8066666666666666
[[25.  0.  0.  7.  3.]
 [ 0. 28. 12. 14.  0.]
 [ 0.  0. 74.  0.  0.]
 [12.  0.  1. 54.  0.]
 [ 9.  0.  0.  0. 61.]]
60
0.9733333333333334
0.8233333333333334
[[13.  0.  0. 21.  4.]
 [ 0. 31. 10.  4.  0.]
 [ 0.  0. 76.  0.  0.]
 [ 5.  3.  0. 64.  0.]
 [ 6.  0.  0.  0. 63.]]
61
0.98
0.8666666666666667
[[29.  0.  0.  7.  3.]
 [ 0. 24.  4.  8.  0.]
 [ 0.  1. 98.  0.  0.]
 [10.  2.  0. 50.  0.]
 [ 5.  0.  0.  0. 59.]]
62
0.9766666666666667
0.85
[[24.  0.  0. 12.  9.]
 [ 0. 27.  5.  4.  0.]
 [ 0.  5. 84.  0.  0.]
 [ 1.  2.  2. 59.  0.]
 [ 5.  0.  0.  0. 61.]]
63
0.9833333333333333
0.81
[[22.  0.  0. 19.  8.]
 [ 0. 30.  8. 11.  0.]
 [ 0.  4. 79.  0.  0.]
 [ 3.  0.  0. 50.  0.]
 [ 4.  0.  0.  0. 62.]]
64
0.9866666666666667
0.79
[[17.  0.  0. 25. 13.]
 [ 0. 33.  7.  6.  0.]
 [ 0.  2. 84.  0.  0.]
 [ 2.  5.  0. 41.  0.]
 [ 3.  0.  0.  0. 62.]]
65
0.9633333333333334
0.8433333333333334
[[10.  0.  0. 16.  7.]
 [ 0. 47.  2.  8.  0.]
 [ 0.  5. 71.  0.  0.]
 [ 1.  3.  0. 60.  0.]
 [ 

In [13]:
print(r_s10_l2_test)
print(np.mean(r_s10_l2_test))
print(np.std(r_s10_l2_test))

print(f_s10_l2_test)
print(np.mean(f_s10_l2_test))
print(np.std(f_s10_l2_test))

[0.82, 0.81, 0.79, 0.7533333333333333, 0.82, 0.82, 0.88, 0.8, 0.8566666666666667, 0.86, 0.8466666666666667, 0.8566666666666667, 0.8666666666666667, 0.8066666666666666, 0.81, 0.8133333333333334, 0.82, 0.8133333333333334, 0.8633333333333333, 0.83, 0.81, 0.8366666666666667, 0.8333333333333334, 0.7966666666666666, 0.7733333333333333, 0.86, 0.8433333333333334, 0.8233333333333334, 0.8333333333333334, 0.7933333333333333, 0.82, 0.8366666666666667, 0.7733333333333333, 0.8133333333333334, 0.7966666666666666, 0.7933333333333333, 0.8566666666666667, 0.7666666666666667, 0.8533333333333334, 0.7666666666666667, 0.8266666666666667, 0.8333333333333334, 0.7766666666666666, 0.8466666666666667, 0.7833333333333333, 0.7966666666666666, 0.83, 0.8, 0.8066666666666666, 0.8633333333333333, 0.78, 0.8033333333333333, 0.81, 0.8333333333333334, 0.8466666666666667, 0.85, 0.85, 0.7933333333333333, 0.8066666666666666, 0.8233333333333334, 0.8666666666666667, 0.85, 0.81, 0.79, 0.8433333333333334, 0.76, 0.836666666666666